services:
    database:
        image: mysql:8.3
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DBNAME}
        volumes:
            - .db:/var/lib/mysql
        ports:
            - "3333:3306"
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
            - /app/.db
        environment:
            - APP_ENV=dev
